# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#

development:
  adapter: postgresql
  database: shared_text_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: shared_text_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
